Updating benchmark-summary to show multiple results side-by-side
FossilOrigin-Name: 45a47abfcaad773121b933b80b831b06821b07a0c9f19b91827e7c06fd98470f

diff --git a/tool/benchmark-summary b/tool/benchmark-summary
--- a/tool/benchmark-summary
+++ b/tool/benchmark-summary
@@ -9,9 +9,9 @@
 
 # /tool/benchmark-summary
 
-if [ $# -lt 2 -o $# -gt 4 ]
+if [ $# -lt 2 ]
 then
-    echo "Usage: $0 PATH_TO_SQLITE3 DATABASE [RUN_ID [TEST_NUMBER]]" >&2
+    echo "Usage: $0 PATH_TO_SQLITE3 DATABASE [RUN_ID]..." >&2
     exit 1
 fi
 
@@ -32,7 +32,7 @@ export LC_NUMERIC
 if [ $# -eq 0 ]
 then
     width="`"$SQLITE3" "$DATABASE" "select max(length(value)) from run_data where key='target';"`"
-    printf "%-64s %-${width}s %-20s %10s\n" RUN_ID TARGET DATE/TIME DURATION
+    printf "%-64s %-${width}s %-20s %11s\n" RUN_ID TARGET DATE/TIME DURATION
     "$SQLITE3" -separator ' ' "$DATABASE" \
 	"select run_id, value from run_data where key='when-run' order by value" | \
     while read id ts
@@ -41,43 +41,59 @@ then
 		"select value from run_data where run_id='$id' and key='target'"`"
 	duration="`"$SQLITE3" "$DATABASE" \
 		 "select sum(value) from test_data where run_id='$id' and key='real-time'"`"
-	printf "%-64s %-${width}s %-20s %10.3f\n" \
+	printf "%-64s %-${width}s %-20s %11.3f\n" \
 	       "$id" "$target" "`date -d@"$ts" +"%Y-%m-%d %H:%M:%S"`" "$duration"
     done
     exit 0
 fi
 
-RUN_ID="$1"; shift
-
-if [ $# -eq 0 ]
-then
+num=1
+hdr=''
+adj=''
+dash='---'
+for RUN_ID
+do
     ts="`"$SQLITE3" "$DATABASE" \
        "select value from run_data where run_id='$RUN_ID' and key='when-run'"`"
     if [ -z "$ts" ]
     then
-	echo "Invalid test ID $RUN_ID" >&2
+	echo "Invalid run ID $RI" >&2
 	exit 1
     fi
     title="`"$SQLITE3" "$DATABASE" \
 	  "select value from run_data where run_id='$RUN_ID' and key='title'"`"
     name="`"$SQLITE3" "$DATABASE" \
 	 "select value from run_data where run_id='$RUN_ID' and key='sqlite-name'"`"
+    [ $# -gt 1 ] && echo "Column $num:"
     echo "Benchmark: $title"
     [ -n "$name" ] && echo "   ($name)"
     echo "Ran at `date -d@"$ts" +"%Y-%m-%d %H:%M:%S"`"
     echo
-    printf "%9s %3s %s\n" TIME NUM NAME
-    "$SQLITE3" -separator ' ' "$DATABASE" \
-	"select test_number, value from test_data where run_id='$RUN_ID' and key='real-time' order by test_number" | \
-    while read num duration
-    do
-	name="`"$SQLITE3" "$DATABASE" \
-	     "select value from test_data where run_id='$RUN_ID' and test_number=$num and key='test-name'"`"
-	printf "%9.3f %3d %s\n" "$duration" "$num" "$name"
-    done
-    exit 0
-fi
+    if [ $# -gt 1 ]
+    then
+	hdr="$hdr`printf %11d $num` "
+	adj="$adj$dash"
+	dash='------'
+	num=`expr $num + 1`
+    else
+	hdr='     TIME'
+    fi
+done
 
-TEST_NUMBER="$1"
-"$SQLITE3" -column "$DATABASE" "select key, value from test_data where run_id='$RUN_ID' and test_number=$TEST_NUMBER order by key"
+[ $# -gt 1 ] && echo "${adj}-TIME$adj"
+printf "%s%4s %s\n" "$hdr" TEST NAME
+FIRST_ID="$1"
+
+"$SQLITE3" -separator ' ' "$DATABASE" \
+    "select test_number, value from test_data where run_id='$FIRST_ID' and key='test-name' order by test_number" | \
+while read num name
+do
+    for RUN_ID
+    do
+	duration="`"$SQLITE3" "$DATABASE" \
+	     "select value from test_data where run_id='$RUN_ID' and test_number=$num and key='real-time'"`"
+	printf "%11.3f " "$duration"
+    done
+    printf "%4d %s\n" "$num" "$name"
+done
 
