Updating build system to allow third party builds which have their own modified versions of sqlite3, so we can use there in benchmarks.  Adding initial mechanism to support BDB backend, currently only the 3rd party build option works.
FossilOrigin-Name: 27d666c8dc308be743c233bc356f724563d0aaf70ed26da48713046c23107708

diff --git a/tool/build-lumo-backend b/tool/build-lumo-backend
--- a/tool/build-lumo-backend
+++ b/tool/build-lumo-backend
@@ -29,13 +29,21 @@ LUMO_DIR="$LUMO_SOURCES/.lumosql-work"
 LUMO_BACKEND_NAME="$(cat "$LUMO_DIR/backend_name")"
 LUMO_BACKEND_VERSION="$(cat "$LUMO_DIR/backend_version")"
 SQLITE3_VERSION="$(cat "$LUMO_DIR/sqlite3_version")"
+TITLE="$(cat "$LUMO_DIR/title")"
 
 # make sure we have all the stuff we need
 OK=true
-if [ ! -d "$LUMO_SOURCES/sqlite3/.lumosql" ]
+if [ -n "$SQLITE3_VERSION" ]
+    then
+    if [ ! -d "$LUMO_SOURCES/sqlite3/.lumosql" ]
+    then
+	echo "Missing sources for 'sqlite3'" >&2
+	OK=false
+    fi
+elif [ -z "$LUMO_BACKEND_NAME" ]
 then
-    echo "Missing sources for 'sqlite3'" >&2
-    OK=false
+    echo "Cannot build without either sqlite3 or a backend!" >&2
+    exit 1
 fi
 if [ -n "$LUMO_BACKEND_NAME" ]
 then
@@ -44,9 +52,6 @@ then
 	echo "Missing sources for '$LUMO_BACKEND_NAME'" >&2
 	OK=false
     fi
-    title="sqlite $SQLITE3_VERSION with $LUMO_BACKEND_NAME $LUMO_BACKEND_VERSION"
-else
-    title="sqlite $SQLITE3_VERSION"
 fi
 $OK || exit 1
 
@@ -67,7 +72,7 @@ LUMO_BUILD="`pwd`"
 if [ -n "$LUMO_BACKEND_NAME" ]
 then
     # build the backend first...
-    export LUMO_SOURCES LUMO_BACKEND_NAME LUMO_BACKEND_VERSION
+    export LUMO_SOURCES LUMO_BACKEND_NAME LUMO_BACKEND_VERSION SQLITE3_VERSION
     cd "$LUMO_BACKEND_NAME"
     sh "$LUMO_SOURCES/$LUMO_BACKEND_NAME/.lumosql/lumo.build"
     cd "$LUMO_BUILD"
@@ -75,13 +80,19 @@ fi
 
 cd sqlite3
 
-# configure
-echo "Configuring $title"
-"$LUMO_SOURCES/sqlite3/configure"
+if [ -n "$SQLITE3_VERSION" ]
+then
+    # configure
+    echo "Configuring $TITLE"
+    "$LUMO_SOURCES/sqlite3/configure"
 
-# build
-echo "Building $title"
-make LUMO_SOURCES="$LUMO_SOURCES" LUMO_BACKEND="$LUMO_BACKEND_NAME" LUMO_BUILD="$LUMO_BUILD"
+    # build
+    echo "Building $TITLE"
+    make LUMO_SOURCES="$LUMO_SOURCES" LUMO_BACKEND="$LUMO_BACKEND_NAME" LUMO_BUILD="$LUMO_BUILD"
+else
+    # we assume that the backend has built its own version of sqlite
+    ln -s "../$LUMO_BACKEND_NAME/sqlite3" .
+fi
 
 # all done
 ./sqlite3 --version
diff --git a/tool/get-lumo-sources b/tool/get-lumo-sources
--- a/tool/get-lumo-sources
+++ b/tool/get-lumo-sources
@@ -89,12 +89,17 @@ fi
 # and make sure the configuration provides at least sqlite3 and the selected
 # backend, in the requested versions
 OK=true
-if [ -d "$CFG_DIR/sqlite3" ]
+if [ -n "$SQLITE3_VERSION" ]
 then
-    not-fork $update -i "$CFG_DIR" -q -v "$SQLITE3_VERSION" sqlite3 > "$LUMO_DIR/sqlite3_info" || OK=false
+    if [ -d "$CFG_DIR/sqlite3" ]
+    then
+	not-fork $update -i "$CFG_DIR" -q -v "$SQLITE3_VERSION" sqlite3 > "$LUMO_DIR/sqlite3_info" || OK=false
+    else
+	echo "Invalid '$CFG_VERSION' configuration directory $CFG_DIR" >&2
+	OK=false
+    fi
 else
-    echo "Invalid '$CFG_VERSION' configuration directory $CFG_DIR" >&2
-    OK=false
+    > "$LUMO_DIR/sqlite3_info"
 fi
 if [ -n "$LUMO_BACKEND_NAME" ]
 then
@@ -111,7 +116,10 @@ fi
 $OK || exit 1
 
 # get sources
-not-fork --no-update -i "$CFG_DIR" -o "$LUMO_SOURCES" -v "$SQLITE3_VERSION" sqlite3 || OK=false
+if [ -n "$SQLITE3_VERSION" ]
+then
+    not-fork --no-update -i "$CFG_DIR" -o "$LUMO_SOURCES" -v "$SQLITE3_VERSION" sqlite3 || OK=false
+fi
 if [ -n "$LUMO_BACKEND_NAME" ]
 then
     not-fork --no-update -i "$CFG_DIR" -o "$LUMO_SOURCES" -v "$LUMO_BACKEND_VERSION" "$LUMO_BACKEND_NAME" || OK=false
